"""Prompts 模块 - 提示词配置"""

from .agents import (
    AgentPrompts,
    SUPERVISOR_PROMPT,
    ATTRACTION_AGENT_PROMPT,
    WEATHER_AGENT_PROMPT,
    HOTEL_AGENT_PROMPT,
    ROUTE_AGENT_PROMPT,
    PLANNER_AGENT_PROMPT,
)

__all__ = [
    "AgentPrompts",
    "SUPERVISOR_PROMPT",
    "ATTRACTION_AGENT_PROMPT",
    "WEATHER_AGENT_PROMPT",
    "HOTEL_AGENT_PROMPT",
    "ROUTE_AGENT_PROMPT",
    "PLANNER_AGENT_PROMPT",
]
